### ISSUE TITLE
Fatal error: Uncaught Error: Call to undefined method Dashboard::vire()

### ISSUE THREAD

**Issue by mqnoy** [RiskyFeryansyahP/percetakan#1]
hi buddy ,

are you typo ? please fix that the line code ,thanks
https://github.com/RiskyFeryansyahP/percetakan/blob/37393bfcd193e38d916ce5dda47666d22d44a0df/app/controller/Dashboard.php#L14

**Comment by RiskyFeryansyahP** [comment]
> hi buddy ,
> 
> are you typo ? please fix that the line code ,thanks
> https://github.com/RiskyFeryansyahP/percetakan/blob/37393bfcd193e38d916ce5dda47666d22d44a0df/app/controller/Dashboard.php#L14


thank you for reminding, i will fix this
